---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nothing-apiserver-deploy # 배포 이름
  namespace: handh # 네임 스페이스 명
  labels:
    app: nothing-apiserver # 배포 이름
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nothing-apiserver # 배포 이름
  template:
    metadata:
      labels:
        app: nothing-apiserver # 배포 이름
    spec:
      containers:
        - name: nothing-apiserver # 컨테이너 이름
          image: "docker.io/c0pperlight/nothing-apiserver:latest" # 이미지명
          imagePullPolicy: Always
          ports: # 컨테이너 내부에서 사용하는 포트 명시
            - name: https
              containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nothing-apiserver-service # 서비스 이름
  namespace: handh
spec:
  selector:
    app: nothing-apiserver # 연결할 Deployment의 이름
  type: LoadBalancer # 서비스 유형 LoadBalancer는 172.17.250.100 ~ 172.17.250.150 중에서 자동 할당하도록 설정되어있음
  ports:
  - name: service-port
    port: 80 # Pod 내부에서 사용하는 포트
    protocol: TCP
