# Generated by Django 5.0.1 on 2024-04-23 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiments', '0005_rename_dataset_id_experiment_dataset_and_more'),
        ('training', '0002_rename_pretraind_model_pretrained'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default=False)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experiment', models.ForeignKey(db_column='experiment_id', default=-1, on_delete=django.db.models.deletion.CASCADE, to='experiments.experiment')),
            ],
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
