# Generated by Django 5.0.1 on 2024-04-24 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_task_delete_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(db_column='', default=-1, on_delete=django.db.models.deletion.CASCADE, to='training.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskQueue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(db_column='task_id', default=-1, on_delete=django.db.models.deletion.CASCADE, to='training.task')),
            ],
        ),
    ]
