# Generated by Django 5.0.1 on 2024-04-24 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_taskpool_taskqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskpool',
            name='task',
            field=models.ForeignKey(db_column='task_id', default=-1, on_delete=django.db.models.deletion.CASCADE, to='training.task'),
        ),
    ]
