# Generated by Django 5.0.4 on 2024-06-24 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_loginsessions_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginsessions',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
