# Generated by Django 5.0.4 on 2024-06-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginsessions',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
