# Generated by Django 5.0.1 on 2024-02-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default=None)),
                ('model_type', models.CharField(max_length=10)),
                ('base_model', models.CharField(max_length=255)),
                ('pretrained', models.BooleanField(default=False)),
                ('source_uri', models.CharField(max_length=1024)),
                ('source_type', models.CharField(default='local', max_length=10)),
                ('run_file_path', models.CharField(default='./run.py', max_length=1024)),
                ('run_options', models.CharField(default='{}', max_length=1024)),
                ('weight_file_path', models.CharField(max_length=1024)),
            ],
        ),
    ]
