# Generated by Django 5.0.1 on 2024-02-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='description',
            field=models.TextField(),
        ),
    ]
