# Generated by Django 5.0.1 on 2024-02-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0004_alter_aimodel_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='base_model',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='run_options',
            field=models.CharField(default=None, max_length=1024),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='source_uri',
            field=models.CharField(default=None, max_length=1024),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='weight_file_path',
            field=models.CharField(default=None, max_length=1024),
        ),
    ]
