# Generated by Django 5.0.1 on 2024-02-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0005_alter_aimodel_base_model_alter_aimodel_run_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='base_model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='run_options',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='source_uri',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='weight_file_path',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
