# Generated by Django 5.0.1 on 2024-02-21 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0006_alter_aimodel_base_model_alter_aimodel_run_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='created_dt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='latest_updated_dt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
