# Generated by Django 5.0.1 on 2024-02-20 23:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0007_aimodel_created_dt_aimodel_latest_updated_dt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='created_dt',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='latest_updated_dt',
        ),
        migrations.AddField(
            model_name='aimodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aimodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
