# Generated by Django 5.0.1 on 2024-02-22 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0008_remove_aimodel_created_dt_and_more'),
        ('experiments', '0002_experiment_model_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AIModel',
            new_name='Model',
        ),
    ]
