# Generated by Django 5.0.1 on 2024-03-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0009_rename_aimodel_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='weight_file_path',
            new_name='weight_file_uri',
        ),
        migrations.AddField(
            model_name='model',
            name='visibility',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='model',
            name='weight_file_type',
            field=models.CharField(default='local', max_length=10),
        ),
        migrations.AlterField(
            model_name='model',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='model',
            name='run_file_path',
            field=models.CharField(default='/run.py', max_length=1024),
        ),
    ]
