# Generated by Django 5.0.4 on 2024-05-08 01:57

from common.code import E
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0011_alter_model_model_type_alter_model_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='envs_info',
            field=models.CharField(default=2, max_length=1024),
        ),
    ]
