# Generated by Django 5.0.4 on 2024-06-10 04:00

import django.db.models.deletion
from common.code import E
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0014_alter_model_result_uri'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='run_file_path',
            new_name='run_command',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='run_options',
            new_name='run_params',
        ),
        migrations.CreateModel(
            name='ModelHyperParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_type', models.CharField(default=0, max_length=10)),
                ('param_name', models.CharField(max_length=255)),
                ('param_key', models.CharField(max_length=255)),
                ('param_value', models.CharField(max_length=255)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_id', to='ai_models.model')),
            ],
        ),
    ]
