# Generated by Django 5.0.4 on 2024-06-10 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0015_rename_run_file_path_model_run_command_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelhyperparam',
            name='model',
            field=models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.CASCADE, related_name='hyper_param', to='ai_models.model'),
        ),
    ]
